set(_CATKIN_CURRENT_PACKAGE "motoman_description")
set(motoman_description_VERSION "0.0.0")
set(motoman_description_MAINTAINER "fukuchi <fukuchi@todo.todo>")
set(motoman_description_PACKAGE_FORMAT "2")
set(motoman_description_BUILD_DEPENDS )
set(motoman_description_BUILD_EXPORT_DEPENDS )
set(motoman_description_BUILDTOOL_DEPENDS "catkin")
set(motoman_description_BUILDTOOL_EXPORT_DEPENDS )
set(motoman_description_EXEC_DEPENDS )
set(motoman_description_RUN_DEPENDS )
set(motoman_description_TEST_DEPENDS )
set(motoman_description_DOC_DEPENDS )
set(motoman_description_DEPRECATED "")