set(_CATKIN_CURRENT_PACKAGE "with_rviz")
set(with_rviz_VERSION "0.0.0")
set(with_rviz_MAINTAINER "tjosh <tjosh@todo.todo>")
set(with_rviz_PACKAGE_FORMAT "2")
set(with_rviz_BUILD_DEPENDS )
set(with_rviz_BUILD_EXPORT_DEPENDS )
set(with_rviz_BUILDTOOL_DEPENDS "catkin")
set(with_rviz_BUILDTOOL_EXPORT_DEPENDS )
set(with_rviz_EXEC_DEPENDS )
set(with_rviz_RUN_DEPENDS )
set(with_rviz_TEST_DEPENDS )
set(with_rviz_DOC_DEPENDS )
set(with_rviz_DEPRECATED "")